/**
 * 拼音音节 → 英文编程词汇映射表（单字映射，去重）
 * 同一拼音取最常见的编程含义
 */
export const PINYIN_TO_ENGLISH: Record<string, string> = {
  // 名词类拼音
  yong: "user", hu: "user",
  lie: "list", biao: "form",
  shu: "data", ju: "data",
  zhuang: "status", tai: "status",
  dan: "popup", chuang: "window",
  hua: "dialog", kuang: "dialog",
  an: "button", niu: "button",
  cai: "menu",
  xiao: "msg", xi: "message",
  xin: "info",
  pei: "config", zhi: "config",
  she: "settings",
  xuan: "option", xiang: "option",
  nei: "content", rong: "content",
  ming: "name", cheng: "name",
  ti: "title",
  miao: "desc",
  di: "address",
  lian: "link", jie: "link",
  lu: "path", jing: "path",
  tu: "image", pian: "image",
  biao2: "icon",
  wen: "text", ben: "text",
  se: "color", yan: "color",
  bei: "bg", jing2: "bg",
  kuan: "width",
  gao: "height",
  liang: "count",
  zong: "total",
  suo: "index", yin: "index",
  jian: "key",
  zhi2: "value",
  lei: "type", xing: "type",
  shi: "time", jian2: "time",
  ri: "date", qi: "date",
  da: "size", xiao2: "size",
  chang: "length",
  fan: "range", wei: "range",
  jie2: "result", guo: "result",
  xiang2: "response", ying: "response",
  qiu: "request", qing: "request",
  cuo: "error", wu: "error",
  yi: "exception", chang2: "exception",
  hui: "callback", diao: "callback",
  shi2: "event", jian3: "event",
  can: "params",
  fan2: "return", hui2: "return",
  ye: "page", ma: "page",
  fen: "pagination",
  mei: "pageSize",
  biao3: "tag", qian: "tag",
  lei2: "category", bie: "category",
  ji: "level",
  quan: "permission", xian: "permission",
  jue: "role", se2: "role",
  lu2: "route", you: "route",
  huan: "cache", cun: "cache",
  ling: "token", pai: "token",
  mi: "password", ma2: "password",
  zhang: "account", hao: "account",
  tou: "avatar", xiang3: "avatar",
  ni: "nickname",
  shou: "phone", ji2: "phone",
  you2: "email", xiang4: "email",
  bei2: "remark", zhu: "remark",
  xiang5: "detail", qing2: "detail",
  zhai: "summary", yao: "summary",
  ban: "version", ben2: "version",
  lai: "source", yuan: "source",
  mu: "target", biao4: "target",
  lai2: "origin", yuan2: "origin",
  zhu2: "theme", ti2: "theme",
  yu: "language", yan2: "language",
  shu2: "number", zi: "number",
  bu: "boolean",
  wen2: "file", jian4: "file",
  jia: "folder", wen3: "folder",
  mu2: "dir", lu3: "dir",
  shu3: "tree", xing2: "tree",
  jie3: "node", dian: "node",
  fu: "parent", ji3: "parent",
  zi2: "child", ji4: "child",
  gen: "root",
  tou2: "header", bu2: "header",
  di2: "footer", bu3: "footer",
  ce: "sidebar", bian: "sidebar",
  rong2: "container", qir: "container",
  bao: "wrapper", guo2: "wrapper",
  ceng: "layer",
  mian: "panel", ban2: "panel",
  ka: "card", pian2: "card",
  kuai: "block", qu: "block",
  qu2: "area", yu2: "area",
  bu4: "section", fen2: "section",
  pian3: "fragment", duan: "fragment",
  mu3: "template", ban3: "template",
  cao: "slot",
  jian5: "component", zu: "component",
  kuai2: "module",
  gong: "tool", jv: "tool",
  fu2: "service", wu2: "service",
  jie4: "api", kou: "api",
  gou: "hook", zi3: "hook",
  cang: "store", ku: "store",
  shang: "context", xia: "context",
  biao5: "id",
  hao2: "no",
  ming2: "rank", ci: "rank",
  pai2: "sort", xu: "sort",
  shun: "order", xu2: "order",
  bu5: "step", chang3: "step",
  jin: "progress", du: "progress",
  bi: "percent", lv: "percent",
  lv2: "rate",
  zui: "max", da2: "max",
  zui2: "min", xiao3: "min",
  ping: "avg", jun: "avg",
  zuo: "coord", biao6: "coord",
  wei2: "position", zhi3: "position",
  pian4: "offset", yi2: "offset",
  jian6: "gap", ju2: "gap",
  bian2: "margin", ju3: "margin",
  nei2: "padding", bian3: "padding",
  bian4: "border", kuang2: "border",
  yin2: "shadow",
  tou3: "opacity", ming3: "opacity",
  dong: "animation", hua2: "animation",
  guo3: "transition",
  ding: "timer", shi3: "timer",
  jian7: "interval", ge: "interval",
  yan3: "delay", chi: "delay",
  chi2: "duration", xu3: "duration",
  pin: "freq", lv3: "freq",
  ci2: "times", shu4: "times",
  zhi4: "log", ji5: "log",
  xiang6: "item", mu4: "item",
  yuan3: "element", su: "element",
  shu5: "attr", xing3: "attr",
  fang: "method", fa: "method",
  han: "func", shu6: "func",
  gou2: "constructor", zao: "constructor",
  li: "instance", shi4: "instance",
  yuan4: "proto", xing4: "proto",
  zhi5: "pointer",
  yin3: "ref", yong2: "ref",
  biao7: "flag", ji6: "flag",
  zhi6: "mark", ji7: "mark",
  fu3: "symbol", hao3: "symbol",
  ge2: "separator", fu4: "separator",
  qian2: "prefix", zhui: "prefix",
  hou: "suffix", zhui2: "suffix",
  mo: "mode", shi5: "mode",
  ze: "rule", lv4: "rule",
  lve: "strategy",
  suan: "algorithm", fa2: "algorithm",
  jie5: "structure", gou3: "structure",
  ge3: "format", shi6: "format",
  yang: "style", shi7: "style",
  lei3: "className", ming4: "className",
  xuan2: "selector", ze2: "selector",
  cha: "query", xun: "query",
  sou: "search", suo2: "search",
  lv5: "filter", guo4: "filter",
  pei2: "match",
  ti3: "replace", huan2: "replace",
  zhuan: "convert", huan3: "convert",
  ying2: "map", she2: "map",
  ming5: "field", duan2: "field",
  zi4: "field", duan3: "field",
  lie2: "column",
  hang: "row",
  ge4: "table", biao8: "table",
  shu7: "input", ru: "input",
  wen4: "textbox", ben3: "textbox",
  xia2: "select", la: "select",
  fu5: "checkbox", xuan3: "checkbox",
  dan2: "radio", xuan4: "radio",
  kai: "switch", guan: "switch",
  hua3: "slider", kuai3: "slider",
  jin2: "progressBar", tiao: "progressBar",
  jia2: "loadingBar", tiao2: "loadingBar",
  shi8: "tip",
  tong: "notification", zhi7: "notification",
  jing3: "warning", gao2: "warning",
  que: "confirm", ren: "confirm",
  cheng2: "success", gong2: "success",
  shi9: "fail", bai: "fail",
  mian2: "breadcrumb", bao2: "breadcrumb",
  bu6: "step", zhou: "step",
  shi10: "timeline", jian8: "timeline",
  hui3: "badge", zhang2: "badge",
  fen3: "divider", ge5: "divider",
  jian9: "space", ju4: "space",
  zha: "grid", lan: "grid",
  bu7: "layout", ju5: "layout",
  xiang7: "responsive", shi11: "responsive",
  duan2b: "breakpoint", dian2: "breakpoint",
  gun: "scroll", dong2: "scroll",
  gun2: "scrollbar", tiao3: "scrollbar",
  mao: "anchor", dian3: "anchor",
  chou: "drawer", ti4: "drawer",
  die: "collapse", zhedie: "collapse",
  shou2: "accordion", feng: "accordion",
  lun: "carousel", bo: "carousel",
  ri2: "calendar",
  chuan: "transfer", suo3: "transfer",
  ji8: "cascade", lian2: "cascade",
  qi2: "popover", pao: "popover",
  ti5: "tooltip", shi12: "tooltip",

  // 动词类拼音
  huo: "get", qv: "get",
  she3: "set", zhi8: "set",
  da3: "open", kai2: "open",
  guan2: "close", bi2: "close",
  ti6: "submit", jiao: "submit",
  shan: "delete", chu: "delete",
  geng: "update", xin2: "update",
  chu2: "handle", li2: "handle",
  chuang2: "create", jian10: "create",
  xin3: "add", jia3: "add",
  yi3: "remove", chu3: "remove",
  bian5: "edit", ji10: "edit",
  xiu: "modify", gai: "modify",
  bao3: "save", cun2: "save",
  jia4: "load", zai: "load",
  shua: "refresh", xin4: "refresh",
  chong: "reset", zhi9: "reset",
  qing3: "clear", kong: "clear",
  sou2: "search", suo4: "search",
  cha2: "query", xun2: "query",
  lv6: "filter",
  pai3: "sort", xu4: "sort",
  xuan5: "select", ze3: "select",
  qu3: "cancel",
  que2: "confirm", ren2: "confirm",
  yan4: "validate", zheng: "validate",
  jian11: "check", cha3: "check",
  jiao2: "verify", yan5: "verify",
  fa3: "send", chu4: "send",
  jie6: "receive", shou3: "receive",
  qing4: "request", qiu2: "request",
  shang2: "upload", chuan2: "upload",
  xia3: "download", zai2: "download",
  dao: "import", ru2: "import",
  chu5: "export", dao2: "export",
  chu6: "init", shi13: "init",
  xiao4: "destroy", hui4: "destroy",
  gua: "mount", zai3: "mount",
  xie: "unmount", zai4: "unmount",
  jian12: "monitor", ting: "monitor",
  bang: "bind", ding2: "bind",
  jie7: "unbind", ding3: "unbind",
  chu7: "trigger", fa4: "trigger",
  pai4: "dispatch",
  guang: "broadcast", bo2: "broadcast",
  ding4: "subscribe", yue: "subscribe",
  qu4: "unsubscribe", yue2: "unsubscribe",
  zhu3: "register", ce2: "register",
  zhu4: "unregister", xiao5: "unregister",
  lian3: "connect", jie8: "connect",
  duan3d: "disconnect", kai3: "disconnect",
  deng: "login", lu4: "login",
  deng2: "logout", chu8: "logout",
  xian2: "show", shi14: "show",
  yin4: "hidden", cang2: "hidden",
  zhan: "expand", kai4: "expand",
  shou4: "collapse", qi3: "collapse",
  gun3: "scroll", dong3: "scroll",
  tuo: "drag", zhuai: "drag",
  fang2: "drop",
  fu6: "copy", zhi10: "copy",
  zhan2: "paste", tie: "paste",
  jian13: "cut",
  che: "undo", xiao6: "undo",
  chong2: "redo", zuo2: "redo",
  qian3: "forward", jin3: "forward",
  hou2: "back", tui: "back",
  tiao4: "navigate", zhuan2: "navigate",
  chong3: "redirect", ding5: "redirect",
  zhuan3: "convert", huan4: "convert",
  ge6: "format", shi15: "format",
  xi3: "parse", xi4: "parse",
  xu5: "serialize",
  fan3: "deserialize",
  bian6: "encode", ma3: "encode",
  jie9: "decode", ma4: "decode",
  jia5: "encrypt", mi2: "encrypt",
  jie10: "decrypt", mi3: "decrypt",
  ya: "compress", suo5: "compress",
  jie11: "decompress", ya2: "decompress",
  he: "merge", bing: "merge",
  chai: "split",
  pin2: "concat", jie12: "concat",
  bian7: "traverse", li3: "traverse",
  die2: "iterate", dai: "iterate",
  ji11: "calc", suan2: "calc",
  bi3: "compare", jiao3: "compare",
  ke: "clone", long: "clone",
  shen: "deep", kao: "deep",
  hun: "mixin", ru3: "mixin",
  zhu5: "inject", ru4: "inject",
  ti7: "provide", gong3: "provide",
  ran: "render", hua4: "render",
  hui5: "draw", zhi11: "draw",
  da4: "print", yin5: "print",
  zan: "pause", ting2: "pause",
  hui6: "resume", fu7: "resume",
  kai5: "start", shi16: "start",
  jie13: "end", shu8: "end",
  ting3: "stop", zhi12: "stop",
  chong4: "retry", shi17: "retry",
  hui7: "rollback", tui2: "rollback",
  yu3: "preload", jia6: "preload",
  lan2: "lazy", jia7: "lazy",
  jie14: "throttle", liu: "throttle",
  fang3: "debounce", dou: "debounce",

  // 状态词类拼音
  xian3: "visible", shi18: "visible",
  yin6: "hidden", cang3: "hidden",
  jia8: "loading", zai5: "loading",
  jin4: "disabled", yong3: "disabled",
  xuan6: "selected", zhong: "selected",
  wan: "done", cheng3: "done",
  ji12: "active", huo2: "active",
  zhan3: "expanded", kai6: "expanded",
  shou5: "collapsed", qi4: "collapsed",
  ke2: "editable", bian8: "editable",
  du2: "readonly", zhi13: "readonly",
  bi4: "required", xu6: "required",
  ke3: "optional", xuan7: "optional",
  you3: "valid", xiao7: "valid",
  wu3: "invalid", xiao8: "invalid",
  kong2: "empty",
  man: "full",
  zai6: "online", xian4: "online",
  li4: "offline",
  yi4: "connected", jie15: "connected",
  yi5: "disconnected", duan4: "disconnected",
  zheng2: "processing", li5: "processing",
  deng3: "pending", dai2: "pending",
  shi19: "is", fou: "is",
};

/**
 * 拼音音节组 → 英文词汇映射（多音节词组，更精准）
 */
export const PINYIN_PHRASE_TO_ENGLISH: Record<string, string> = {
  // 常见双音节名词
  yonghu: "user",
  liebiao: "list",
  shuju: "data",
  zhuangtai: "status",
  danchuang: "popup",
  huakuang: "dialog",
  biaodan: "form",
  anniu: "button",
  caidan: "menu",
  xiaoxi: "message",
  xinxi: "info",
  peizhi: "config",
  shezhi: "settings",
  xuanxiang: "option",
  neirong: "content",
  mingcheng: "name",
  biaoti: "title",
  miaoshu: "desc",
  dizhi: "address",
  lianjie: "link",
  lujing: "path",
  tupian: "image",
  tubiao: "icon",
  wenben: "text",
  yanse: "color",
  beijing: "bg",
  kuandu: "width",
  gaodu: "height",
  shuliang: "count",
  zongshu: "total",
  suoyin: "index",
  jianming: "key",
  jiazhi: "value",
  leixing: "type",
  shijian: "time",
  riqi: "date",
  daxiao: "size",
  changdu: "length",
  fanwei: "range",
  jieguo: "result",
  xiangying: "response",
  qingqiu: "request",
  cuowu: "error",
  yichang: "exception",
  huidiao: "callback",
  shijian2: "event",
  canshu: "params",
  fanhui: "return",
  yema: "page",
  fenye: "pagination",
  meiye: "pageSize",
  biaoqian: "tag",
  fenlei: "category",
  jibie: "level",
  quanxian: "permission",
  juese: "role",
  luxian: "route",
  huancun: "cache",
  lingpai: "token",
  mima: "password",
  zhanghao: "account",
  touxiang: "avatar",
  nicheng: "nickname",
  shouji: "phone",
  youxiang: "email",
  beizhu: "remark",
  xiangqing: "detail",
  zhaiyao: "summary",
  banben: "version",
  laiyuan: "source",
  mubiao: "target",
  zhuti: "theme",
  yuyan: "language",
  shuzi: "number",
  buer: "boolean",
  wenjian: "file",
  wenjianjia: "folder",
  mulu: "dir",
  shuxing: "tree",
  jiedian: "node",
  fujie: "parent",
  zijie: "child",
  genjie: "root",
  toubu: "header",
  dibu: "footer",
  cebian: "sidebar",
  rongqi: "container",
  baoguo: "wrapper",
  cengji: "layer",
  mianban: "panel",
  kapian: "card",
  kuaiji: "block",
  quyu: "area",
  bufen: "section",
  pianduan: "fragment",
  muban: "template",
  chacao: "slot",
  zujian: "component",
  mokuai: "module",
  gongju: "tool",
  fuwu: "service",
  jiekou: "api",
  gouzi: "hook",
  cangku: "store",
  shangxia: "context",
  biaoshi: "id",
  bianhao: "no",
  paiming: "rank",
  paixu: "sort",
  shunxu: "order",
  buchang: "step",
  jindu: "progress",
  bifenbi: "percent",
  bili: "rate",
  zuida: "max",
  zuixiao: "min",
  pingjun: "avg",
  zuobiao: "coord",
  weizhi: "position",
  pianyi: "offset",
  jianju: "gap",
  bianju: "margin",
  neibian: "padding",
  biankuang: "border",
  yinying: "shadow",
  toushi: "opacity",
  donghua: "animation",
  guodu: "transition",
  dingshi: "timer",
  jiange: "interval",
  yanchi: "delay",
  chixu: "duration",
  pinlv: "freq",
  cishu: "times",
  rizhi: "log",
  liebiaoxiang: "item",
  yuansu: "element",
  shuxing2: "attr",
  fangfa: "method",
  hanshu: "func",
  gouzaohan: "constructor",
  shili: "instance",
  yuanxing: "proto",
  zhiying: "pointer",
  yinyong: "ref",
  biaoji: "flag",
  biaoji2: "mark",
  fuhao: "symbol",
  fengefu: "separator",
  qianzhui: "prefix",
  houzhui: "suffix",
  moshi: "mode",
  guize: "rule",
  celve: "strategy",
  suanfa: "algorithm",
  jiegou: "structure",
  geshi: "format",
  yangshi: "style",
  leiming: "className",
  xuanzeqi: "selector",
  chaxun: "query",
  sousuo: "search",
  lvguo: "filter",
  pipei: "match",
  tihuan: "replace",
  zhuanhuan: "convert",
  yingshe: "map",
  ziduan: "field",
  liebiao2: "column",
  hang2: "row",
  biaoge: "table",
  shuru: "input",
  wenbenkuang: "textbox",
  xiala: "select",
  fuxuan: "checkbox",
  danxuan: "radio",
  kaiguan: "switch",
  huakuai: "slider",
  jindutiao: "progressBar",
  jiazaitiao: "loadingBar",
  tishi: "tip",
  tongzhi: "notification",
  jinggao: "warning",
  queren: "confirm",
  chenggong: "success",
  shibai: "fail",
  mianbaoxie: "breadcrumb",
  buzhou: "step",
  shijianzhou: "timeline",
  huibiao: "badge",
  fengexian: "divider",
  jianju2: "space",
  shage: "grid",
  buju: "layout",
  xiangying2: "responsive",
  duandian: "breakpoint",
  gundong: "scroll",
  gundongtiao: "scrollbar",
  maodian: "anchor",
  chouti: "drawer",
  zhedie: "collapse",
  shoufengqin: "carousel",
  rili: "calendar",
  chuanruo: "transfer",
  jilian: "cascade",
  qipao: "popover",
  gongjuhint: "tooltip",

  // 动词词组
  huoqu: "get",
  shezhi2: "set",
  dakai: "open",
  guanbi: "close",
  tijiao: "submit",
  shanchu: "delete",
  gengxin: "update",
  chuli: "handle",
  chuangjian: "create",
  tianjia: "add",
  yichu: "remove",
  bianji: "edit",
  xiugai: "modify",
  baocun: "save",
  jiazai: "load",
  shuaxin: "refresh",
  chongzhi: "reset",
  qingkong: "clear",
  sousuo2: "search",
  chaxun2: "query",
  lvguo2: "filter",
  paixu2: "sort",
  xuanze: "select",
  quxiao: "cancel",
  queren2: "confirm",
  yanzheng: "validate",
  jiancha: "check",
  jiaoyan: "verify",
  fasong: "send",
  jieshou: "receive",
  qingqiu2: "request",
  shangchuan: "upload",
  xiazai: "download",
  daoru: "import",
  daochu: "export",
  chushihua: "init",
  xiaohui: "destroy",
  guazai: "mount",
  xiezai: "unmount",
  jianshi: "monitor",
  bangding: "bind",
  jiebang: "unbind",
  chufa: "trigger",
  paifa: "dispatch",
  guangbo: "broadcast",
  dingyue: "subscribe",
  quxiao2: "unsubscribe",
  zhuce: "register",
  zhuxiao: "unregister",
  lianjie2: "connect",
  duankai: "disconnect",
  denglu: "login",
  dengchu: "logout",
  xianshi: "show",
  yincang: "hidden",
  zhankai: "expand",
  shouqi: "collapse",
  gundong2: "scroll",
  tuozhuai: "drag",
  fangzhi: "drop",
  fuzhi: "copy",
  niantie: "paste",
  jianqie: "cut",
  chexiao: "undo",
  chongzuo: "redo",
  qianjin: "forward",
  houtui: "back",
  tiaozhuan: "navigate",
  chongdingxiang: "redirect",
  zhuanhuan2: "convert",
  geshihua: "format",
  jiexi: "parse",
  xuliehua: "serialize",
  fanxulie: "deserialize",
  bianma: "encode",
  jiema: "decode",
  jiami: "encrypt",
  jiemi: "decrypt",
  yasuo: "compress",
  jieya: "decompress",
  hebing: "merge",
  chaifen: "split",
  pinjie: "concat",
  bianli: "traverse",
  diedai: "iterate",
  jisuan: "calc",
  bijiao: "compare",
  kebei: "clone",
  shenkao: "deep",
  hunru: "mixin",
  zhuru: "inject",
  tigong: "provide",
  ranran: "render",
  huizhi: "draw",
  dayin: "print",
  zanting: "pause",
  huifu: "resume",
  kaishi: "start",
  jieshu: "end",
  tingzhi: "stop",
  chongshi: "retry",
  huigun: "rollback",
  yujiazai: "preload",
  lanjiazai: "lazy",
  jielv: "throttle",
  fangdou: "debounce",

  // ========== 新增：常见复合词组拼音映射 ==========
  // 用户相关
  yonghuliebiao: "userList",
  yonghuxinxi: "userInfo",
  yonghuxiangqing: "userDetail",
  yonghuguanli: "userManagement",
  yonghuzhongxin: "userCenter",
  yonghuming: "username",
  yonghuid: "userId",
  yonghujuese: "userRole",
  yonghuquanxian: "userPermission",

  // 订单相关
  dingdanliebiao: "orderList",
  dingdanxiangqing: "orderDetail",
  dingdanhao: "orderNo",
  dingdanzhuangtai: "orderStatus",
  dingdanguanli: "orderManagement",
  dingdanchaxun: "orderQuery",
  dingdanjine: "orderAmount",

  // 商品相关
  shangpinliebiao: "productList",
  shangpinxiangqing: "productDetail",
  shangpintupian: "productImage",
  shangpinmingcheng: "productName",
  shangpinjiage: "productPrice",
  shangpinkucun: "productStock",
  shangpinfenlei: "productCategory",

  // 支付相关
  zhifufangshi: "paymentMethod",
  zhifuzhuangtai: "paymentStatus",
  zhifujine: "paymentAmount",
  zhifushijian: "paymentTime",
  zhifuchenggong: "paymentSuccess",
  zhifushibai: "paymentFailed",

  // 表单相关
  biaodanshuju: "formData",
  biaodanyanzheng: "formValidation",
  biaodantijiao: "formSubmit",
  biaodanziduan: "formField",
  biaodancuowu: "formError",

  // 列表相关
  liebiaoshuju: "listData",
  liebiaoxiang: "listItem",
  liebiaojiazai: "listLoading",
  liebiaoweikong: "listEmpty",
  liebiaoshuaxin: "listRefresh",

  // 分页相关
  dangqianye: "currentPage",
  meiyetiaoshu: "pageSize",
  zongyeshu: "totalPages",
  zongtiaoshu: "totalCount",
  fenyeqi: "paginator",

  // 搜索相关
  sousuojieguo: "searchResult",
  sousuotiaojian: "searchCondition",
  sousuolishi: "searchHistory",
  sousuojianyi: "searchSuggestion",
  remensousuo: "hotSearch",

  // 筛选相关
  shaixuantiaojian: "filterCondition",
  shaixuanjieguo: "filterResult",
  gaojishaixuan: "advancedFilter",
  shaixuanzhongzhi: "filterReset",

  // 排序相关
  shengxu: "ascending",
  jiangxu: "descending",
  morenpaixu: "defaultSort",
  zidingyipaixu: "customSort",

  // 状态相关
  jiazaizhong: "loading",
  jiazaiwancheng: "loaded",
  jiazaisahibai: "loadFailed",
  tijiaozhong: "submitting",
  tijiaochenggong: "submitted",
  tijiaoshibai: "submitFailed",
  baocunzhong: "saving",
  baocunchenggong: "saved",
  baocunshibai: "saveFailed",
  shanchuchenggong: "deleted",
  shanchushibai: "deleteFailed",
  gengxinchenggong: "updated",
  gengxinshibai: "updateFailed",

  // 按钮相关
  qurenanniu: "confirmButton",
  quxiaoanniu: "cancelButton",
  tijiaoanniu: "submitButton",
  zhongzhianniu: "resetButton",
  sousuoanniu: "searchButton",
  tianjiaanniu: "addButton",
  bianjianniu: "editButton",
  shanchuanniu: "deleteButton",
  daochuanniu: "exportButton",
  daoruanniu: "importButton",
  shuaxinanniu: "refreshButton",
  fanhuianniu: "backButton",
  guanbianniu: "closeButton",

  // 弹窗相关
  qurendanchuang: "confirmDialog",
  tishidanchuang: "alertDialog",
  jinggaodanchuang: "warningDialog",
  chenggongdanchuang: "successDialog",
  cuowudanchuang: "errorDialog",
  danchuangbiaoti: "dialogTitle",
  danchuangneirong: "dialogContent",
  danchuangguanbi: "dialogClose",

  // 表格相关
  biaogeshuju: "tableData",
  biaogelie: "tableColumn",
  biaogehang: "tableRow",
  biaogebutou: "tableHeader",
  biaogeshenti: "tableBody",
  biaogepaixu: "tableSort",
  biaogeshaixuan: "tableFilter",
  biaogefenye: "tablePagination",

  // 侧边栏相关
  cebianlancaidan: "sidebarMenu",
  cebianlanzhedie: "sidebarCollapse",
  cebianlanzhankai: "sidebarExpand",

  // 导航相关
  daohangcaidan: "navMenu",
  daohanglan: "navigationBar",
  mianbaoxiedaohang: "breadcrumbNav",
  biaoqiandaohang: "tabNav",

  // 头部相关
  toubudaohang: "headerNav",
  toubucaidan: "headerMenu",
  toubulogo: "headerLogo",

  // 底部相关
  dibudaohang: "footerNav",
  dibubanquan: "footerCopyright",
  dibulianjie: "footerLink",

  // 卡片相关
  kapianbiaoti: "cardTitle",
  kapianneirong: "cardContent",
  kapiancaozuo: "cardAction",
  kapianliebiao: "cardList",

  // 图表相关
  zhuzhuangtu: "barChart",
  zhexiantu: "lineChart",
  bingtu: "pieChart",
  sandiantu: "scatterChart",
  tubiaoshuju: "chartData",
  tubiaopeizhi: "chartConfig",
  tubiaobioti: "chartTitle",

  // 上传相关
  shangchuanwenjian: "uploadFile",
  shangchuantupian: "uploadImage",
  shangchuanjindu: "uploadProgress",
  shangchuanchenggong: "uploadSuccess",
  shangchuanshibai: "uploadFailed",

  // 下载相关
  xiazaiwenjian: "downloadFile",
  xiazaijindu: "downloadProgress",
  xiazaichenggong: "downloadSuccess",
  xiazaishibai: "downloadFailed",

  // 导入导出相关
  daorushuju: "importData",
  daochushuju: "exportData",
  daorumoban: "importTemplate",
  daochumoban: "exportTemplate",

  // 权限相关
  quanxianguanli: "permissionManagement",
  quanxianshezhi: "permissionSetting",
  quanxianliebiao: "permissionList",
  jueseguanli: "roleManagement",
  jueseliebiao: "roleList",
  juesequanxian: "rolePermission",

  // 日志相关
  caozuorizhi: "operationLog",
  dengrlrizhi: "loginLog",
  cuowurizhi: "errorLog",
  rizhiliebiao: "logList",
  rizhixiangqing: "logDetail",

  // 通知相关
  tongzhiliebiao: "notificationList",
  tongzhixiangqing: "notificationDetail",
  weidutongzhi: "unreadNotification",
  yidutongzhi: "readNotification",
  tongzhishezhi: "notificationSetting",

  // 消息相关
  xiaoxiliebiao: "messageList",
  xiaoxixiangqing: "messageDetail",
  weiduxiaoxi: "unreadMessage",
  yiduxiaoxi: "readMessage",
  xiaoxizhongxin: "messageCenter",

  // 设置相关
  xitongshezhi: "systemSetting",
  gerenshezhi: "personalSetting",
  anquanshezhi: "securitySetting",
  yinsishezhi: "privacySetting",

  // 个人中心相关
  gerenxinxi: "personalInfo",
  gerenziliao: "profile",
  xiugaimima: "changePassword",
  bangdingshouji: "bindPhone",
  bangdingyouxiang: "bindEmail",

  // 登录注册相关
  dengluyemian: "loginPage",
  zhuceyemian: "registerPage",
  wangjimima: "forgotPassword",
  chongzhimima: "resetPassword",
  yanzhengma: "verificationCode",
  duanxinyanzhengma: "smsCode",
  youxiangyanzhengma: "emailCode",

  // 数据统计相关
  shujutongji: "dataStatistics",
  shujugailan: "dataOverview",
  shujubaobiao: "dataReport",
  shujufenxi: "dataAnalysis",
  shujudaochu: "dataExport",

  // 仪表盘相关
  yibiaopan: "dashboard",
  shujukapian: "dataCard",
  tongjikapian: "statsCard",
  kuaijiecaozuo: "quickAction",

  // 动词短语拼音映射
  huoquyonghu: "getUser",
  huooquliebiao: "getList",
  huoquxiangqing: "getDetail",
  huoqushuju: "getData",
  huoquxinxi: "getInfo",
  huoquipeizhi: "getConfig",
  huoquzhuangtai: "getStatus",
  huoquanxian: "getPermission",
  huoqujuese: "getRole",
  huoqucaidan: "getMenu",
  huoquzidian: "getDict",
  huoquxuanxiang: "getOption",

  shezhiyonghu: "setUser",
  shezhizhuangtai: "setStatus",
  shezhipeizhi: "setConfig",
  shezhiquanxian: "setPermission",
  shezhijuese: "setRole",

  chuangjianyonghu: "createUser",
  chuangjiandingdan: "createOrder",
  chuangjianshangpin: "createProduct",
  chuangjianjuese: "createRole",
  chuangjiancaidan: "createMenu",
  chuangjianzidian: "createDict",

  shanchuyonghu: "deleteUser",
  shanchuindingdan: "deleteOrder",
  shanchushangpin: "deleteProduct",
  shanchujuese: "deleteRole",
  shanchucaidan: "deleteMenu",
  shanchuzidian: "deleteDict",

  gengxinyonghu: "updateUser",
  gengxindingdan: "updateOrder",
  gengxinshangpin: "updateProduct",
  gengxinjuese: "updateRole",
  gengxincaidan: "updateMenu",
  gengxinzidian: "updateDict",

  chaxunyonghu: "queryUser",
  chaxundingdan: "queryOrder",
  chaxunshangpin: "queryProduct",
  chaxunrizhi: "queryLog",

  sousuoyonghu: "searchUser",
  sousuodingdan: "searchOrder",
  sousuoshangpin: "searchProduct",

  daoruyonghu: "importUser",
  daochuyonghu: "exportUser",
  daorudingdan: "importOrder",
  daochudingdan: "exportOrder",
  daorushangpin: "importProduct",
  daochushangpin: "exportProduct",

  shangchuantouxiang: "uploadAvatar",
  shangchuantupian: "uploadImage",
  shangchuanwenjian: "uploadFile",
  xiazaimoban: "downloadTemplate",
  xiazaiwenjian: "downloadFile",

  yonghudenglu: "userLogin",
  yonghuzhuce: "userRegister",
  yonghudengchu: "userLogout",
  wangjimima: "forgotPassword",
  chongzhimima: "resetPassword",
  xiugaimima: "changePassword",

  fenpeiquanxian: "assignPermission",
  fenpeijuese: "assignRole",
  jianchaquanxian: "checkPermission",
  yanzhengquanxian: "verifyPermission",

  qiyongzhuangtai: "enableStatus",
  jinyongzhuangtai: "disableStatus",
  qiehuanzhuangtai: "toggleStatus",
  gengxinzhuangtai: "updateStatus",

  tijiaoshenpi: "submitApproval",
  shenpitongguo: "approve",
  shenpijvjuv: "reject",
  chehuishenpi: "withdrawApproval",

  fasongtongzhi: "sendNotification",
  biaojvweidu: "markAsRead",
  biaojvweidu: "markAsUnread",
  shanchutongzhi: "deleteNotification",
  qingkongtongzhi: "clearNotification",

  fasongxiaoxi: "sendMessage",
  jieshouxiaoxi: "receiveMessage",
  shanchuxiaoxi: "deleteMessage",
  qingkongxiaoxi: "clearMessage",

  tongjishuju: "statisticsData",
  fenxishuju: "analyzeData",
  daochubaobiao: "exportReport",
  shengchengbaobiao: "generateReport",
};
